export const PermissionFunctionKeys = {
  // Radar / Operação
  RADAR_VIEW: "RADAR_VIEW",
  RADAR_REFRESH: "RADAR_REFRESH",

  // Radar / Operação - abas individuais
  RADAR_GERAL_VIEW: "RADAR_GERAL_VIEW",
  RADAR_PROBLEMAS_VIEW: "RADAR_PROBLEMAS_VIEW",
  RADAR_DEMANDAS_TAB_VIEW: "RADAR_DEMANDAS_TAB_VIEW",
  RADAR_INCIDENTES_VIEW: "RADAR_INCIDENTES_VIEW",
  RADAR_SOLICITACOES_VIEW: "RADAR_SOLICITACOES_VIEW",
  RADAR_CATALOGO_VIEW: "RADAR_CATALOGO_VIEW",
  RADAR_EFICIENCIA_VIEW: "RADAR_EFICIENCIA_VIEW",
  RADAR_OBSERVABILIDADE_VIEW: "RADAR_OBSERVABILIDADE_VIEW",

  // Roadmap Geral (timeline consolidada de tickets_global)
  ROADMAP_GERAL_VIEW: "ROADMAP_GERAL_VIEW",

  // Demandas
  DEMANDAS_VIEW: "DEMANDAS_VIEW",
  MINHAS_ATIVIDADES_VIEW: "MINHAS_ATIVIDADES_VIEW",

  // Team
  TEAM_VIEW: "TEAM_VIEW",
  TEAM_EDIT: "TEAM_EDIT",

  // User (UserDetailsModal)
  USER_CSR_VIEW: "USER_CSR_VIEW",
  USER_RATECARD_VIEW: "USER_RATECARD_VIEW",

  // Configurações / Operação
  SETTINGS_VIEW: "SETTINGS_VIEW",
  PLANEJAMENTO_VIEW: "PLANEJAMENTO_VIEW",
  CONFIGURACOES_VIEW: "CONFIGURACOES_VIEW",

  // Administração
  ADMIN_ALL: "ADMIN_ALL",
};
