// Catálogo de campos da carga Jira × SGT
// sync: S=sempre | P=primeira_carga | N=nunca(SGT protegido) | C=calculado
// origem: jira | sgt | calculado | carga
// Formato: [campo, label, categoria, origem, sync, jiraField]
const _raw = [
  ['issueKey','Chave do ticket','Identificação','jira','S','key'],
  ['jiraId','ID interno Jira','Identificação','jira','S','id'],
  ['issueUrl','URL do ticket','Identificação','calculado','S','—'],
  ['summary','Resumo','Conteúdo','jira','S','summary'],
  ['description','Descrição','Conteúdo','jira','S','description'],
  ['environment','Ambiente','Conteúdo','jira','S','environment'],
  ['status','Status','Status','jira','S','status.name'],
  ['statusCategory','Categoria do status','Status','jira','S','status.statusCategory.name'],
  ['statusCategoryKey','Chave da categoria','Status','jira','S','status.statusCategory.key'],
  ['resolution','Resolução','Status','jira','S','resolution.name'],
  ['statusHistory','Histórico de status','Status','jira','S','changelog (expand)'],
  ['assignee / assigneeEmail','Responsável','Pessoas','jira','S','assignee'],
  ['reporter / reporterEmail','Solicitante','Pessoas','jira','S','reporter'],
  ['creator','Criador','Pessoas','jira','S','creator.displayName'],
  ['projectKey / projectName','Projeto','Classificação','jira','S','project'],
  ['issueType','Tipo de issue','Classificação','jira','S','issuetype.name'],
  ['priority','Prioridade Jira','Classificação','jira','S','priority.name'],
  ['escopo','Escopo','Classificação','carga','S','—'],
  ['syncBatch','Batch de sync','Classificação','carga','S','—'],
  ['labels','Labels','Classificação','jira','S','labels'],
  ['components','Componentes','Classificação','jira','S','components[].name'],
  ['parentKey','Epic/Parent','Vínculos','jira','S','parent.key'],
  ['epicKey','Epic Link','Vínculos','jira','S','Epic Link'],
  ['linkedWorkItems','Work items vinculados','Vínculos','jira','S','Parent Link'],
  ['issueLinksDetailed','Links detalhados','Vínculos','jira','S','issuelinks'],
  ['commentCount','Qtd. comentários','Contagens','jira','S','comment.total'],
  ['attachmentCount','Qtd. anexos','Contagens','jira','S','attachment.length'],
  ['subtaskCount','Qtd. subtarefas','Contagens','jira','S','subtasks.length'],
  ['reopenCount','Qtd. reaberturas','Contagens','jira','S','Quantidade de Reaberturas'],
  ['empresa','Empresa','Custom Jira','jira','S','Empresa'],
  ['fornecedor','Fornecedor','Custom Jira','jira','S','Fornecedor'],
  ['naturezaIniciativa','Natureza da Iniciativa','Custom Jira','jira','S','Natureza da Iniciativa'],
  ['grupoSuporte','Grupo de Suporte','Custom Jira','jira','S','Grupo de Suporte'],
  ['grupoSolucionador','Grupo Solucionador','Custom Jira','jira','S','Grupo Solucionador'],
  ['fornecedorTi','Fornecedor TI','Custom Jira','jira','S','Fornecedor TI'],
  ['demandaFast','Demanda Fast','Custom Jira','jira','S','Demanda Fast[Dropdown]'],
  ['torreAtuacao','Torre de Atuação','Custom Jira','jira','S','Torre de Atuação da Demanda'],
  ['fornecedoresDropdown','Fornecedores (dropdown)','Custom Jira','jira','S','Fornecedores'],
  ['severidade','Severidade','Custom Jira','jira','S','Severidade[Dropdown]'],
  ['demandaVulnerabilidade','Demanda Vulnerabilidade','SGT Gerenciado','sgt','N','—'],
  ['sistemasImpactados','Sistemas Impactados','Custom Jira','jira','S','Sistemas Impactados (customfield_10325)'],
  ['responsavelExecucao','Responsável Execução','Custom Jira','jira','S','Responsável pela Execução'],
  ['createdAt','Criado em','Datas Jira','jira','S','created'],
  ['updatedAt','Atualizado em','Datas Jira','jira','S','updated'],
  ['resolvedAt','Resolvido em','Datas Jira','jira','S','resolutiondate'],
  ['dueDate','Data limite','Datas Jira','jira','S','duedate'],
  ['dataAprovacaoEfsr','Data Aprovação EF/SR','Datas Custom','jira','S','customfield_10259'],
  ['dataInicioAtendimentoPlanejada','Data Início Atend. Planejada','Datas Custom','jira','S','customfield_10434'],
  ['dataInicioAtendimento','Data Início Atendimento','Datas Custom','jira','S','customfield_10260'],
  ['dataAprovacaoQaPlanejada','Data Aprovação QA Planejada','Datas Custom','jira','S','customfield_10435'],
  ['dataInicioHomologacaoPlanejada','Data Início Homolog. Planejada','Datas Custom','jira','S','customfield_10261'],
  ['dataInicioHomologacaoEfetiva','Data Início Homolog. Efetiva','Datas Custom','jira','S','customfield_10431'],
  ['dataFimHomologacaoPlanejada','Data Fim Homolog. Planejada','Datas Custom','jira','S','customfield_10262'],
  ['dataFimHomologacaoEfetiva','Data Fim Homolog. Efetiva','Datas Custom','jira','S','customfield_10432'],
  ['dataEntregaProducaoPrevista','Data Entrega Produção Prevista','Datas Custom','jira','S','customfield_10263'],
  ['estimativaHoras','Estimativa de Horas','Datas Custom','jira','S','customfield_10437'],
  ['dataFimPlanejado','Data Fim Planejado','Datas Custom','jira','S','customfield_16711'],
  ['planejamentoHorasDemandaFast','Planejamento Horas Demanda Fast','Datas Custom','jira','S','customfield_14314'],
  // Calculados pelo sistema
  ['syncedAt','Timestamp do sync','Calculados','calculado','C','—'],
  ['agingDays','Aging em dias','Calculados','calculado','C','—'],
  // prioridadeInterna: inicializado do Jira no 1º upsert, depois protegido
  ['prioridadeInterna','Prioridade Interna','SGT Gerenciado','sgt','P','priority.name'],
  // Campos SGT - NUNCA sobrescritos pelo sync Jira
  ['responsavelAtual','Responsável Atual','SGT Gerenciado','sgt','N','—'],
  ['dataPrevisao','Data de Previsão','SGT Gerenciado','sgt','N','—'],
  ['observacaoAdicional','Observação Adicional','SGT Gerenciado','sgt','N','—'],
  ['estimativaMacro','Estimativa Macro','Custom Jira','jira','S','Estimativa Macro'],
  ['impedimento','Impedimento','SGT Gerenciado','sgt','N','—'],
  ['impedido','Impedido','SGT Gerenciado','sgt','N','—'],
  ['radarFieldsUpdatedAt','Atualizado (campos radar)','SGT Gerenciado','sgt','N','—'],
  ['estimativaTotal','Estimativa Total','Custom Jira','jira','S','Estimativa Total'],
  ['estimativaInterna','Estimativa Interna','SGT Gerenciado','sgt','N','—'],
  ['squadPrincipal','Squad Principal','SGT Gerenciado','sgt','N','—'],
  ['squad','Squad','SGT Gerenciado','sgt','N','—'],
  ['percentualConclusao','% Conclusão','SGT Gerenciado','sgt','N','—'],
  ['responsavelDesenvolvimento','Resp. Desenvolvimento','SGT Gerenciado','sgt','N','—'],
  ['responsavelTesteInterno','Resp. Teste Interno','SGT Gerenciado','sgt','N','—'],
  ['dataFimDesenvolvimento','Data Fim Desenvolvimento','SGT Gerenciado','sgt','N','—'],
  ['dataFimTesteInterno','Data Fim Teste Interno','SGT Gerenciado','sgt','N','—'],
  ['dataFimTesteQa','Data Fim Teste QA','SGT Gerenciado','sgt','N','—'],
  ['dataFimHomologacao','Data Fim Homologação','SGT Gerenciado','sgt','N','—'],
  ['dataConclusao','Data Conclusão','SGT Gerenciado','sgt','N','—'],
  ['observacao','Observação','SGT Gerenciado','sgt','N','—'],
  ['cicloId','ID do Ciclo','SGT Gerenciado','sgt','N','—'],
  ['ticketsVinculados','Tickets Vinculados','SGT Gerenciado','sgt','N','—'],
];

const SYNC_EXPAND = { S: 'sempre', P: 'primeira_carga', N: 'nunca', C: 'calculado' };

export const CARGA_FIELD_CATALOG = _raw.map(([campo, label, categoria, origem, sync, jiraField]) => ({
  campo, label, categoria, origem, jiraField,
  sync: SYNC_EXPAND[sync] || sync,
}));

export const CATEGORIAS = [...new Set(_raw.map((r) => r[2]))];
